## 一 创建数组对象

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

方法一 使用array函数，通过list创建数组对象

In [2]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [5]:
array2=np.array([[1,2,3],[4,5,6]])
array2
print(array2)

[[1 2 3]
 [4 5 6]]


方法二 使用arange函数，指定取值范围和跨度创建数组对象

In [4]:
array3 = np.arange(0,20,2)
array3
print(array3)

[ 0  2  4  6  8 10 12 14 16 18]


In [1]:
%pwd

'D:\\Yan Shi Data\\【1】先进技术部\\【3】研发项目\\大数据智能化\\python学习\\Python-100-Days-sy\\Jupyterlab files'

方法七 使用numpy.random模块的函数生成随机数创建数组对象，产生[1，100)范围的随机整数构成三位数组

In [8]:
array12=np.random.randint(1,100,(3,4,5))
print(array12)


[[[90  3 14 82 23]
  [94 85 39 49 45]
  [ 4 80 52 85  8]
  [15 11  7 36 53]]

 [[34 82 59 35 84]
  [39 81  2 33 28]
  [16 90 44 52 17]
  [95 17 70 25 64]]

 [[35 66 37 26 17]
  [71 86 17 25 12]
  [88 51  4 52 76]
  [18 36 15 33 36]]]


方法十 读取图片获取对应的三位数组

In [12]:
array16=plt.imread(r'D:\Yan Shi Data\【1】先进技术部\【3】研发项目\大数据智能化\python学习\Python-100-Days-sy\Day01-15\code\Day15\res\guido.jpg')
print(array16)

[[[ 36  33  28]
  [ 36  33  28]
  [ 36  33  28]
  ...
  [ 32  31  29]
  [ 32  31  27]
  [ 31  32  26]]

 [[ 37  34  29]
  [ 38  35  30]
  [ 38  35  30]
  ...
  [ 31  30  28]
  [ 31  30  26]
  [ 30  31  25]]

 [[ 38  35  30]
  [ 38  35  30]
  [ 38  35  30]
  ...
  [ 30  29  27]
  [ 30  29  25]
  [ 29  30  25]]

 ...

 [[239 178 123]
  [237 176 121]
  [235 174 119]
  ...
  [ 78  68  56]
  [ 75  67  54]
  [ 73  65  52]]

 [[238 177 120]
  [236 175 118]
  [234 173 116]
  ...
  [ 82  70  58]
  [ 78  68  56]
  [ 75  66  51]]

 [[238 176 119]
  [236 175 118]
  [234 173 116]
  ...
  [ 84  70  61]
  [ 81  69  57]
  [ 79  67  53]]]


## 二 数组对象的属性
* size属性：获取数组元素的个数
* shape属性：获取数组的形状

In [13]:
array17 = np.arange(1, 100, 2)
array18 = np.random.rand(3, 4)
print(array16.size)
print(array17.size)
print(array18.size)
print(array16.shape)
print(array17.shape)
print(array18.shape)

1125000
50
12
(750, 500, 3)
(50,)
(3, 4)


* ndim属性：获取数组的维度

In [15]:
print(array16.ndim)
print(array17.ndim)
print(array18.ndim)

3
1
2


## 三数组的索引运算
Numpy的ndarray对象可以进行索引和切片操作，通过索引可以获取或修改数组中的元素，通过切片操作可以取出数组的一部分，切片操作也成为切片索引